name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # cache node_modules
    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-*

    # Create env file for Telegram bot
    - name: 'Create env file'
      env:
        CHATID_VAL: ${{ secrets.CHATID }}
        BOTKEY_VAL: ${{ secrets.BOTKEY }}
      run: |
        touch .env
        echo "CHATID=$CHATID_VAL" >> .env
        echo "BOTKEY=$BOTKEY_VAL" >> .env

    # install dependencies if the cache did not hit
    - name: Install dependencies
      run: npm install

    # run build script
    - name: Build VuePress site
      run: npm run docs:build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MY_PRIVATE_KEY_DEPLOY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: |
        echo "Before ssh-keyscan:"
        cat ~/.ssh/known_hosts || echo "No known_hosts file found"      
        for i in {1..5}; do
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts && break
          echo "Retrying in 5 seconds..."
          sleep 5
        done
        echo "After ssh-keyscan:"
        cat ~/.ssh/known_hosts        

    - name: Deploy with rsync
      run: rsync -avz ./docs/.vuepress/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/personal/
